@URL = http://{{HOST}}:{{PORT}}/{{API_PREFIX}}/{{API_VERSION}}

@AUTH_TOKEN = {{loginAdmin.response.body.token}}


### Login as Admin
# @name loginAdmin
POST {{URL}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin@123"
}


### Get all users (default pagination)
GET {{URL}}/users
Authorization: Bearer {{AUTH_TOKEN}}

### Get all users with pagination
GET {{URL}}/users?page=1&limit=5
Authorization: Bearer {{AUTH_TOKEN}}

### Get deleted users
GET {{URL}}/users/deleted
Authorization: Bearer {{AUTH_TOKEN}}

### Get deleted users with pagination
GET {{URL}}/users/deleted?page=1&limit=5
Authorization: Bearer {{AUTH_TOKEN}}

### Get user by ID
GET {{URL}}/users/1

### Create Admin user
POST {{URL}}/users
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "email": "admin@example.com",
  "password": "admin@123",
  "role": "ADMIN"
}

### Create Editor user
POST {{URL}}/users
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "email": "editor@example.com",
  "password": "editor@123",
  "role": "EDITOR"
}

### Create Viewer user
POST {{URL}}/users
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "email": "viewer@example.com",
  "password": "viewer@123",
  "role": "VIEWER"
}

### Update user email
PUT {{URL}}/users/1
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "email": "newemail@example.com",
  "password": "newpass@123"
}

### Partial update user (change role)
PATCH {{URL}}/users/1
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "role": "EDITOR"
}

### Soft delete user
DELETE {{URL}}/users/1
Authorization: Bearer {{AUTH_TOKEN}}

### Hard delete user (permanent)
DELETE {{URL}}/users/1/permanent
Authorization: Bearer {{AUTH_TOKEN}}

### Recover deleted user
POST {{URL}}/users/1/recover
Authorization: Bearer {{AUTH_TOKEN}}