### Get all users (default pagination)
GET http://localhost:8025/api/v1/users

### Get all users with pagination
GET http://localhost:8025/api/v1/users?page=1&limit=5

### Get deleted users
GET http://localhost:8025/api/v1/users/deleted

### Get deleted users with pagination
GET http://localhost:8025/api/v1/users/deleted?page=1&limit=5

### Get user by ID
GET http://localhost:8025/api/v1/users/1

### Create Admin user
POST http://localhost:8025/api/v1/users
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin@123",
  "role": "ADMIN"
}

### Create Editor user
POST http://localhost:8025/api/v1/users
Content-Type: application/json

{
  "email": "editor@example.com",
  "password": "editor@123",
  "role": "EDITOR"
}

### Create Viewer user
POST http://localhost:8025/api/v1/users
Content-Type: application/json

{
  "email": "viewer@example.com",
  "password": "viewer@123",
  "role": "VIEWER"
}

### Update user email
PUT http://localhost:8025/api/v1/users/1
Content-Type: application/json

{
  "email": "newemail@example.com",
  "password": "newpass@123"
}

### Partial update user (change role)
PATCH http://localhost:8025/api/v1/users/1
Content-Type: application/json

{
  "role": "EDITOR"
}

### Soft delete user
DELETE http://localhost:8025/api/v1/users/1

### Hard delete user (permanent)
DELETE http://localhost:8025/api/v1/users/1/permanent

### Recover deleted user
POST http://localhost:8025/api/v1/users/1/recover